[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**/*"]

[functions.node_bundler_flags]
  format = "esm"

[functions.chat]
  timeout = 30
  memory = 1024
  environment = { GROQ_API_KEY = "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" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "vite" 