[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**/*"]

[functions.node_bundler_flags]
  format = "esm"

[functions.chat]
  timeout = 30
  memory = 1024

[build.environment]
  BACKEND_URL = "https://portfolio-backend-zwr8.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "vite" 