services:
  - type: web
    name: portfolio-backend
    env: node
    rootDir: backend
    buildCommand: npm ci --production
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /health 